#!/bin/bash

SCRIPT=$(readlink -f $0)
export METTA_DIR=$(dirname $SCRIPT)
cd $METTA_DIR

if [ "${1}" == "--tee" ] ; then
shift 1
[ -z "$TEE_FILE" ] && export TEE_FILE="${METTA_DIR}/tee.ansi"
[ -z "$TYPESCRIPT" ] && TYPESCRIPT=1 exec /usr/bin/script -f -e -a ${TEE_FILE} -c "TYPESCRIPT=1 $0 --tee $@"
echo start $0 $@
fi

echo METTA_DIR=$METTA_DIR
cd $METTA_DIR
touch $TEE_FILE
chmod 777 $TEE_FILE

export SWIPL_OPTIONS="${@}"
if [[ $SWIPL_OPTIONS == *" -- "* ]];
then
    echo "$SWIPL_OPTIONS"
else
    SWIPL_OPTIONS="-- ${SWIPL_OPTIONS}"
fi

#killall -9 xterm

export BCMD="cd '${METTA_DIR}' ; pwd ; export TEE_FILE='${TEE_FILE}' ; exec swipl ${SWIPL_OPTIONS} -l metta_vspace/pyswip/metta_interp.pl -- --args "$@"

echo BCMD=$BCMD
sleep 0.1

# % 642,202,528 inferences, 104.676 CPU in 104.682 seconds (100% CPU, 6135124 Lips)
# swipl -g "time(load_files([mumetta_cache/metta_db_temp_cache],[qcompile(auto)])),halt."

stty sane


