/*
; Total         Atoms (Atomspace size): ...................................................... 40,097
;               ConceptNodes: ............................................................... 107,035
;               Random samples: ............................................................. 127,980
;               Total Memory Used: ............................................................. 101M
;               Runtime (days:hh:mm:ss): ................................................. 0:00:03:33
*/

:- dynamic maybe_corisponds/2.
:- module_transparent maybe_corisponds/2.


maybe_corisponds('ConceptMapFn'('Allele_used_in_model_(symbol)', 8, disease_model_annotations/12), 'ConceptMapFn'(current_symbol, 3, synonym/6)).
maybe_corisponds('ConceptMapFn'('Allele_used_in_model_(symbol)', 8, disease_model_annotations/12), 'ConceptMapFn'(description, 6, stocks/7)).
maybe_corisponds('ConceptMapFn'('Allele_used_in_model_(symbol)', 8, disease_model_annotations/12), 'ConceptMapFn'(uniquename, 5, stocks/7)).
maybe_corisponds('ConceptMapFn'('AlleleSymbol', 2, fbal_to_fbgn/4), 'ConceptMapFn'('Allele_used_in_model_(symbol)', 8, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('Based_on_orthology_with_(symbol)', 10, disease_model_annotations/12), 'ConceptMapFn'('Human_gene_symbol', 5, dmel_human_orthologs_disease/8)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 1, best_gene_summary/4)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 1, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 1, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 1, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 2, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 2, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('GeneName', 3, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'(gene_fullname, 3, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'(gene_fullname, 3, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBan', 5, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'(annotation_ID, 6, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FB_group_name', 3, gene_group/7), 'ConceptMapFn'('FB_group_name', 3, gene_groups_HGNC/4)).
maybe_corisponds('ConceptMapFn'('FB_group_name', 3, gene_group/7), 'ConceptMapFn'(gene_group_name, 2, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FB_group_name', 3, gene_groups_HGNC/4), 'ConceptMapFn'('FB_group_name', 3, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FB_group_name', 3, gene_groups_HGNC/4), 'ConceptMapFn'(gene_group_name, 2, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FB_group_symbol', 2, gene_group/7), 'ConceptMapFn'('FB_group_symbol', 2, gene_groups_HGNC/4)).
maybe_corisponds('ConceptMapFn'('FB_group_symbol', 2, gene_groups_HGNC/4), 'ConceptMapFn'('FB_group_symbol', 2, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FB_group_symbol', 2, gene_groups_HGNC/4), 'ConceptMapFn'('Parent_FB_group_symbol', 5, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FB_group_symbol', 2, gene_groups_HGNC/4), 'ConceptMapFn'('Parent_FB_group_symbol', 5, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBal', 1, fbal_to_fbgn/4), 'ConceptMapFn'('FBal', 7, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('FBal', 7, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 1, synonym/6)).
maybe_corisponds('ConceptMapFn'('FBan', 5, fbgn_annotation_ID/6), 'ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4)).
maybe_corisponds('ConceptMapFn'('FBan', 5, fbgn_annotation_ID/6), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBan', 5, fbgn_annotation_ID/6), 'ConceptMapFn'(annotation_ID, 6, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBan', 5, fbgn_annotation_ID/6), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBan', 5, fbgn_annotation_ID/6), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBan', 5, fbgn_annotation_ID/6), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('FBan', 5, fbgn_annotation_ID/6), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgg', 1, gene_group/7), 'ConceptMapFn'('FBgg', 1, gene_groups_HGNC/4)).
maybe_corisponds('ConceptMapFn'('FBgg', 1, gene_group/7), 'ConceptMapFn'(gene_group_id, 1, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgg', 1, gene_groups_HGNC/4), 'ConceptMapFn'('FBgg', 1, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgg', 1, gene_groups_HGNC/4), 'ConceptMapFn'('FBgg', 4, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgg', 1, gene_groups_HGNC/4), 'ConceptMapFn'('FBgg', 4, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgg', 1, gene_groups_HGNC/4), 'ConceptMapFn'(gene_group_id, 1, 'Dmel_enzyme'/11)).

maybe_corisponds('ConceptMapFn'('FBgn', 1, automated_gene_summaries/2), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, automated_gene_summaries/2), 'ConceptMapFn'('FBgn', 4, gene_functional_complementation/5)).

maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 1, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 1, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 1, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 2, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 2, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, best_gene_summary/4), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).

maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 1, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 1, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 2, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 2, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, disease_model_annotations/12), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).

maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 1, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 2, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 2, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_paralogs/11), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).

maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 1, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 2, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 2, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 1, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 2, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 2, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 1, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 2, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 2, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 1, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 2, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 2, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 1, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 2, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 2, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_snapshots/5), 'ConceptMapFn'('FBgn', 2, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_snapshots/5), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_snapshots/5), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_snapshots/5), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_snapshots/5), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_snapshots/5), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_snapshots/5), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_snapshots/5), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_snapshots/5), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_snapshots/5), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_snapshots/5), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 1, gene_snapshots/5), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_functional_complementation/5), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_functional_complementation/5), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_functional_complementation/5), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_functional_complementation/5), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_functional_complementation/5), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_functional_complementation/5), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_functional_complementation/5), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_functional_complementation/5), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_functional_complementation/5), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_functional_complementation/5), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_functional_complementation/5), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 2, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_rpkm_report/12), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_rpkm_report/12), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_rpkm_report/12), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_rpkm_report/12), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_rpkm_report/12), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_rpkm_report/12), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 2, gene_rpkm_report/12), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4), 'ConceptMapFn'('FBgn', 4, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, gene_map_table/6), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, gene_map_table/6), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, gene_map_table/6), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, gene_map_table/6), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, gene_map_table/6), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 3, gene_map_table/6), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 6, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 6, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 6, dmel_paralogs/11), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 6, dmel_paralogs/11), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 6, gene_group/7), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('FBgn', 6, gene_group/7), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 6, gene_group/7), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 6, pathway_group/7), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('FBgn', 6, pathway_group/7), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('FBpp', 3, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBpp', 10, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('FBrf', 1, fbrf_pmid_pmcid_doi/7), 'ConceptMapFn'('FBrf', 12, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('FBrf', 1, fbrf_pmid_pmcid_doi/7), 'ConceptMapFn'('FBrf', 5, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBrf', 1, fbrf_pmid_pmcid_doi/7), 'ConceptMapFn'('FBrf', 6, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBrf', 3, entity_publication/4), 'ConceptMapFn'('FBrf', 12, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('FBrf', 3, entity_publication/4), 'ConceptMapFn'('FBrf', 4, allele_genetic_interactions/4)).
maybe_corisponds('ConceptMapFn'('FBrf', 3, entity_publication/4), 'ConceptMapFn'('FBrf', 5, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBrf', 3, entity_publication/4), 'ConceptMapFn'('FBrf', 6, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBrf', 4, allele_genetic_interactions/4), 'ConceptMapFn'('FBrf', 12, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('FBrf', 4, allele_genetic_interactions/4), 'ConceptMapFn'('FBrf', 5, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('FBrf', 4, allele_genetic_interactions/4), 'ConceptMapFn'('FBrf', 6, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBrf', 5, gene_functional_complementation/5), 'ConceptMapFn'('FBrf', 12, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('FBrf', 5, gene_functional_complementation/5), 'ConceptMapFn'('FBrf', 6, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('FBrf', 6, gene_genetic_interactions/6), 'ConceptMapFn'('FBrf', 12, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('FBtr', 2, fbgn_fbtr_fbpp/3), 'ConceptMapFn'('FBtr', 8, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7)).
maybe_corisponds('ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4), 'ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4), 'ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4), 'ConceptMapFn'(gene_fullname, 3, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7)).
maybe_corisponds('ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12), 'ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12), 'ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12), 'ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('GeneName', 3, gene_snapshots/5), 'ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4)).
maybe_corisponds('ConceptMapFn'('GeneName', 3, gene_snapshots/5), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('GeneName', 3, gene_snapshots/5), 'ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('GeneName', 3, gene_snapshots/5), 'ConceptMapFn'(gene_fullname, 3, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('GeneName', 3, gene_snapshots/5), 'ConceptMapFn'(gene_fullname, 5, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('GeneName', 3, gene_snapshots/5), 'ConceptMapFn'(gene_name, 9, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('GeneName', 3, gene_snapshots/5), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('GeneName', 3, gene_snapshots/5), 'ConceptMapFn'(species, 2, organism_list/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11), 'ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11), 'ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11), 'ConceptMapFn'('GeneSymbol', 3, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11), 'ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11), 'ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 3, gene_rpkm_report/12), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 3, gene_rpkm_report/12), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 3, gene_rpkm_report/12), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 3, gene_rpkm_report/12), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4), 'ConceptMapFn'(ortholog_gene_symbol, 3, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'('Genetic_map_position', 2, 'cyto-genetic-seq'/4), 'ConceptMapFn'(recombination_loc, 4, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7), 'ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7), 'ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7), 'ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7), 'ConceptMapFn'(gene_name, 9, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7), 'ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7), 'ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7), 'ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7), 'ConceptMapFn'(gene_fullname, 3, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7), 'ConceptMapFn'(gene_name, 9, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('HGNC', 3, dmel_human_orthologs_disease/8), 'ConceptMapFn'('HGNC', 9, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6), 'ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11), 'ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11), 'ConceptMapFn'(gene_fullname, 3, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'('Summary', 4, best_gene_summary/4), 'ConceptMapFn'(gene_snapshot_text, 5, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'(annotation_ID, 6, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'(annotation_ID, 6, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'(annotation_ID, 6, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'(current_symbol, 2, gene_map_table/6), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'(current_symbol, 2, gene_map_table/6), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'(current_symbol, 2, gene_map_table/6), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'(current_symbol, 2, gene_map_table/6), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(current_symbol, 2, gene_map_table/6), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'(current_symbol, 3, synonym/6), 'ConceptMapFn'(description, 6, stocks/7)).
maybe_corisponds('ConceptMapFn'(current_symbol, 3, synonym/6), 'ConceptMapFn'(uniquename, 5, stocks/7)).
maybe_corisponds('ConceptMapFn'(cytogenetic_loc, 5, gene_map_table/6), 'ConceptMapFn'(estimated_cytogenetic_location, 6, insertion_mapping/7)).
maybe_corisponds('ConceptMapFn'(gene_fullname, 3, gene_rpkm_matrix/170), 'ConceptMapFn'(gene_fullname, 5, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(gene_fullname, 3, gene_rpkm_matrix/170), 'ConceptMapFn'(gene_name, 9, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'(gene_fullname, 5, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'(gene_name, 9, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'(gene_type, 2, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'(gene_type, 4, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'(gene_type, 2, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'(so_term_name, 3, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'(gene_type, 4, gene_rpkm_matrix/170), 'ConceptMapFn'(so_term_name, 3, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'(gene_type, 4, gene_rpkm_matrix/170), 'ConceptMapFn'(transcript_type, 7, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(identical_protein, 4, dmel_unique_protein_isoforms/4), 'ConceptMapFn'(polypeptide_symbol, 11, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(polypeptide_symbol, 11, fbgn_fbtr_fbpp_expanded/11), 'ConceptMapFn'(representative_protein, 3, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'(so_term_name, 3, dmel_gene_sequence_ontology_annotations/4), 'ConceptMapFn'(transcript_type, 7, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('GeneSymbol', 3, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 1, best_gene_summary/4)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 1, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 1, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 1, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 2, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 2, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 6, gene_group/7)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 6, pathway_group/7)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9)).
maybe_corisponds('ConceptMapFn'(_, 1, fbgn_uniprot/4), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'(_, 1, genotype_phenotype/7), 'ConceptMapFn'('AlleleSymbol', 2, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'(_, 1, genotype_phenotype/7), 'ConceptMapFn'(allele_symbol, 1, allele_genetic_interactions/4)).
maybe_corisponds('ConceptMapFn'(_, 1, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBrf', 1, fbrf_pmid_pmcid_doi/7)).
maybe_corisponds('ConceptMapFn'(_, 1, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBrf', 12, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'(_, 1, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBrf', 3, entity_publication/4)).
maybe_corisponds('ConceptMapFn'(_, 1, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBrf', 4, allele_genetic_interactions/4)).
maybe_corisponds('ConceptMapFn'(_, 1, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBrf', 5, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'(_, 1, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBrf', 6, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'(_, 1, pmid_fbgn_uniprot/5), 'ConceptMapFn'(_, 7, genotype_phenotype/7)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('Dmel_gene_symbol', 1, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('Dmel_gene_symbol', 2, dmel_human_orthologs_disease/8)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('FBan', 5, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('Gene_Symbol', 2, best_gene_summary/4)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('Gene_symbol', 2, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('GeneSymbol', 2, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('GeneSymbol', 2, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('GeneSymbol', 4, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, gene_group/7)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('Interacting_gene_symbol', 3, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('Paralog_GeneSymbol', 7, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'('Starting_gene_symbol', 1, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'(_, 1, fbgn_NAseq_Uniprot/9)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'(annotation_ID, 6, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'(gene_symbol, 2, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(_, 2, fbgn_uniprot/4), 'ConceptMapFn'(gene_symbol, 8, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'(_, 2, genotype_phenotype/7), 'ConceptMapFn'('FBal', 1, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'(_, 2, genotype_phenotype/7), 'ConceptMapFn'('FBal', 2, allele_genetic_interactions/4)).
maybe_corisponds('ConceptMapFn'(_, 2, pmid_fbgn_uniprot/5), 'ConceptMapFn'('PMID', 2, fbrf_pmid_pmcid_doi/7)).
maybe_corisponds('ConceptMapFn'(_, 2, pmid_fbgn_uniprot/5), 'ConceptMapFn'('PubMed', 4, entity_publication/4)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('Dmel_gene', 1, dmel_human_orthologs_disease/8)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 1, best_gene_summary/4)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 1, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 1, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 1, gene_rpkm_matrix/170)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 2, gene_rpkm_report/12)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 3, fbal_to_fbgn/4)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 4, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 6, dmel_paralogs/11)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_uniprot/4), 'ConceptMapFn'('FB_gene_symbol', 2, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_uniprot/4), 'ConceptMapFn'('FBan', 5, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_uniprot/4), 'ConceptMapFn'('Group_member_FB_gene_symbol', 7, pathway_group/7)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_uniprot/4), 'ConceptMapFn'(annotation_ID, 6, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_uniprot/4), 'ConceptMapFn'(current_symbol, 2, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_uniprot/4), 'ConceptMapFn'(gene_symbol, 1, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_uniprot/4), 'ConceptMapFn'(gene_symbol, 2, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'(_, 3, fbgn_uniprot/4), 'ConceptMapFn'(gene_symbol, 4, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(_, 3, genotype_phenotype/7), 'ConceptMapFn'('GeneName', 3, gene_snapshots/5)).
maybe_corisponds('ConceptMapFn'(_, 3, genotype_phenotype/7), 'ConceptMapFn'(current_fullname, 4, synonym/6)).
maybe_corisponds('ConceptMapFn'(_, 3, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBgn', 1, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'(_, 3, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBgn', 1, dmel_unique_protein_isoforms/4)).
maybe_corisponds('ConceptMapFn'(_, 3, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy1_overlaps/2)).
maybe_corisponds('ConceptMapFn'(_, 3, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBgn', 1, fbgn_exons2affy2_overlaps/2)).
maybe_corisponds('ConceptMapFn'(_, 3, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBgn', 1, fbgn_fbtr_fbpp/3)).
maybe_corisponds('ConceptMapFn'(_, 3, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBgn', 2, gene_genetic_interactions/6)).
maybe_corisponds('ConceptMapFn'(_, 3, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBgn', 3, fbgn_annotation_ID/6)).
maybe_corisponds('ConceptMapFn'(_, 3, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBgn', 3, fbgn_fbtr_fbpp_expanded/11)).
maybe_corisponds('ConceptMapFn'(_, 3, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBgn', 3, gene_map_table/6)).
maybe_corisponds('ConceptMapFn'(_, 3, pmid_fbgn_uniprot/5), 'ConceptMapFn'('FBgn', 7, 'Dmel_enzyme'/11)).
maybe_corisponds('ConceptMapFn'(_, 3, pmid_fbgn_uniprot/5), 'ConceptMapFn'(_, 1, fbgn_uniprot/4)).
maybe_corisponds('ConceptMapFn'(_, 3, pmid_fbgn_uniprot/5), 'ConceptMapFn'(gene_primary_id, 1, dmel_gene_sequence_ontology_annotations/4)).
maybe_corisponds('ConceptMapFn'(_, 4, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'('EST_accession', 6, cDNA_clone/6)).
maybe_corisponds('ConceptMapFn'(_, 4, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'(accession, 4, genomic_clone/4)).
maybe_corisponds('ConceptMapFn'(_, 4, fbgn_NAseq_Uniprot/9), 'ConceptMapFn'(clone_name, 3, cDNA_clone/6)).
maybe_corisponds('ConceptMapFn'(_, 4, fbgn_uniprot/4), 'ConceptMapFn'(_, 6, fbgn_NAseq_Uniprot/9)).
maybe_corisponds('ConceptMapFn'(_, 5, pmid_fbgn_uniprot/5), 'ConceptMapFn'(_, 4, fbgn_uniprot/4)).
maybe_corisponds('ConceptMapFn'(_, 7, genotype_phenotype/7), 'ConceptMapFn'('FBrf', 12, disease_model_annotations/12)).
maybe_corisponds('ConceptMapFn'(_, 7, genotype_phenotype/7), 'ConceptMapFn'('FBrf', 3, entity_publication/4)).
maybe_corisponds('ConceptMapFn'(_, 7, genotype_phenotype/7), 'ConceptMapFn'('FBrf', 4, allele_genetic_interactions/4)).
maybe_corisponds('ConceptMapFn'(_, 7, genotype_phenotype/7), 'ConceptMapFn'('FBrf', 5, gene_functional_complementation/5)).
maybe_corisponds('ConceptMapFn'(_, 7, genotype_phenotype/7), 'ConceptMapFn'('FBrf', 6, gene_genetic_interactions/6)).


